### ISSUE TITLE
サーバーサイドで認証・認可をしていないようで、curl 等でリクエストを送ると他人のデータの改竄・削除が出来てしまう

### ISSUE THREAD

**Issue by kachick** [nizi24/PolPa-api#21]
セキュリティ issue なのですが、習作アプリだと思うのでこちらでそのまま報告させていただきます。
自分の作った user は id 50 なのですが

<img width="960" alt="スクリーンショット 2021-02-15 3 49 42" src="https://user-images.githubusercontent.com/1180335/107886260-14a7d480-6f42-11eb-8d24-eb34e022b9c4.png">

この方を

<img width="1074" alt="スクリーンショット 2021-02-15 3 50 33" src="https://user-images.githubusercontent.com/1180335/107886266-1a051f00-6f42-11eb-8510-f68a7220ef48.png">

この様に名前変更出来ます。

<img width="1088" alt="スクリーンショット 2021-02-15 3 55 55" src="https://user-images.githubusercontent.com/1180335/107886267-1b364c00-6f42-11eb-93da-cb161524a0d5.png">

また、この方の作られた time_reports も

<img width="1145" alt="スクリーンショット 2021-02-15 3 57 40" src="https://user-images.githubusercontent.com/1180335/107886268-1bcee280-6f42-11eb-9e57-31b530bec350.png">

この様に削除できてしまいました。

firebase にログインを任せているということですが、APIサーバーでその情報を使っていないようなコードに見られました。
他の方のところでも見られたのですが、 https://github.com/kuromitsu0104/gadget-app/issues/67 と同じ様な問題を抱えているのかなと。

**Comment by nizi24** [comment]
ご指摘ありがとうございます。
複数のアプリケーションで同じような問題が見られるのは、[Qiitaの記事](https://b.hatena.ne.jp/entry/s/qiita.com/saongtx7/items/d97ef5aec393e704fd3f) を参考にして認証周りが作られているからだと思われます。(記事は削除された模様、理由は不明)
- 現在、出先で詳細な調査ができない
- アクティブユーザーがいない

ので、後ほど対応策を検討します。

**Comment by kachick** [comment]
>複数のアプリケーションで同じような問題が見られるのは、Qiitaの記事 を参考にして認証周りが作られているからだと思われます。(記事は削除された模様、理由は不明)

なるほど、そんな記事があったのですね、腑に落ちました！

**Comment by nizi24** [comment]
Idトークンを使用した認証を実装することにしました。
[ID トークンを検証する | Firebase](https://firebase.google.com/docs/auth/admin/verify-id-tokens?hl=ja)

フロントでFirebaseからIdトークンを取得し、サーバーでIdトークンの署名を検証することで認証するつもりです。
Idトークンの検証には、[gem](https://github.com/Findy/firebase-auth-id_token_keeper)を使用することにしました。

**Comment by nizi24** [comment]
Application_controllerに以下を実装しました。
extract_access_tokenでトークンを検証するメソッドを呼び出しています。
トークンから得られた、uidを使用することによってユーザーを特定します。
それぞれのcontrollerで、before_actionを使用してauthorizeを呼び出します。

https://github.com/nizi24/PolPa-api/blob/7e70b93b36fe59c93c428670a8325bbbc5f45b62/app/controllers/application_controller.rb#L1-L24

**Comment by nizi24** [comment]
フロントでは、FirebaseからIdトークンを取得して、storeに保存します。
[参考: クライアントで ID トークンを取得する](https://firebase.google.com/docs/auth/admin/verify-id-tokens?hl=ja#retrieve_id_tokens_on_clients)

https://github.com/nizi24/PolPa-front/blob/48b4fa1c76bfb97c4c73da23655479bc3f042142/plugins/auth-check.js#L32-L36

**Comment by nizi24** [comment]
認可が必要なHTTPリクエストの際には、Authorization: Bearer ヘッダをリクエストに含めて送信します。

https://github.com/nizi24/PolPa-front/blob/48b4fa1c76bfb97c4c73da23655479bc3f042142/pages/users/setting/account.vue#L252-L257

**Comment by nizi24** [comment]
各controllerでは、ApplicationControllerに実装されているcurrent_userを呼び出すことによって、ユーザーを特定します。

https://github.com/nizi24/PolPa-api/blob/7e70b93b36fe59c93c428670a8325bbbc5f45b62/app/controllers/v1/users_controller.rb#L50-L52

**Comment by nizi24** [comment]
問題がなさそうなら、その他の場所にも変更を加えて行きます。

**Comment by kachick** [comment]
なるほど良さそうですね！ 自分は firebase 自体を触ったことがないのですが、とても妥当な改修方針では無いかと思いました！ この短時間でありがとうございます！ 👍

**Comment by nizi24** [comment]
この方針で進めて行きたいと思います。
こちらこそご指摘ありがとうございました！
